# pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "stocking"
version = "0.1.0"
description = "股票财务分析工具"
dependencies = []  # 可选，如果你有外部依赖

[tool.setuptools.packages.find]
where = ["src"]